name: Build, push, deploy

on:
  workflow_call:
    inputs:
      image-repository:
        type: string
        required: true
      image-tags:
        type: string
        required: false
        default: latest
      keel-fqdn:
        type: string
        required: true
      docker-context-path:
        type: string
        required: false
        default: .
      docker-registry:
        type: string
        default: ghcr.io
        required: false
      add-date-tag:
        type: boolean
        default: false
        required: false
      build-args:
        type: string
        required: false
    secrets:
      keel-password:
        required: true

jobs:
  build-push-deploy:
    name: Build, push and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: add-date-tag-if-needed
        run: |
          if [ "$ADD_DATE_TAG" = true ]; then
            IMAGE_TAGS+=($(date +%F))
          fi
          echo "image-tags=${IMAGE_TAGS[@]}" >> ${GITHUB_OUTPUT}
        env:
          ADD_DATE_TAG: ${{ inputs.add-date-tag }}
          IMAGE_TAGS: ${{ inputs.image-tags }}
      - id: image-metadata
        uses: LoicGombeaud/image-metadata@main
        with:
          image-repository: ${{ inputs.image-repository }}
          image-tags: ${{ steps.add-date-tag-if-needed.outputs.image-tags }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.docker-context-path }}
          tags: ${{ steps.image-metadata.outputs.full-image-tags }}
          build-args: ${{ inputs.build-args }}
      - run: |
          echo IMAGE_NAME=${IMAGE_NAME}
          for tag in ${IMAGE_TAGS[@]}; do
            curl \
              -u plan-de-circulation:${{ secrets.keel-password }} \
              -d "{\"name\":\"${IMAGE_NAME}\", \"tag\":\"${tag}\"}" \
              -H "Content-Type: application/json" \
              -X POST https://$KEEL_FQDN/v1/webhooks/native
          done
        env:
          IMAGE_NAME: ${{ steps.image-metadata.outputs.image-name }}
          IMAGE_TAGS: ${{ steps.add-date-tag-if-needed.outputs.image-tags }}
          KEEL_FQDN: ${{ inputs.keel-fqdn }}
